function U = RandNE_Combine(U_list,weights)
% Inputs:
%   U_list: a list of decomposed parts, generated by RandNE_Projection
%   weights: a vector of weights for each order, w_0 ... w_q
% Outputs:
%   U: final embedding vector

if size(U_list,1) < length(weights)
    error('Weights not consistent');
end
U = weights(1) * U_list{1};
for i = 2:length(weights)
    U = U + (weights(i) * U_list{i});
end

end